### ISSUE TITLE
Talm air-gapped installation

### ISSUE THREAD

**Issue by RaSerge** [aenix-io/talm#15]
Hello!
I'm tried to adopt talm for air-gapped lab installation.
by define [ntp servers](https://www.talos.dev/v1.7/talos-guides/configuration/time-sync/), [registries mirrors]( https://www.talos.dev/v1.7/advanced/air-gapped/) and upload images from`talosctl image default`
It seems that talm installation dont't use that images  (registry download metrics counters at 0)
Which default images version we should have in local registry?
Can you provide some additional info how to adapt talm installation for air-gapped environment,

**Comment by RaSerge** [comment]
I will try to implement work from this PR https://github.com/aenix-io/cozystack/pull/175

**Comment by kvaps** [comment]
I think the easiest way at the moment is to specify registry-mirrors in talos configuration

https://www.talos.dev/v1.7/talos-guides/configuration/pull-through-cache/#using-harbor-as-a-caching-registry

**Comment by kvaps** [comment]
Also installation image can be specified using talos machine config:

```
machine:
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.29.0-rc.1
    install:
        image: ghcr.io/siderolabs/installer:v1.6.0-beta.1
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.29.0-rc.1
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.29.0-rc.1
    proxy:
        image: registry.k8s.io/kube-proxy:v1.29.0-rc.1
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.29.0-rc.1
    etcd:
        image: gcr.io/etcd-development/etcd:v3.5.11-arm64
```
