### ISSUE TITLE
Bug generate template

### ISSUE THREAD

**Issue by Karabass-OFF** [aenix-io/talm#25]
My k8s network is 192.168.201.0/24.
Talm correctly generates interfaces, routes, name servers.
My command to generate template:
``` bash talm -n 192.168.201.201.10 -e 192.168.201.201.10 template -t templates/controlplane.yaml > nodes/kub-t10.yaml ```
Does not correctly generate validSubnets, endpoint, advertisedSubnets as shown below. Should be values from network 192.168.201.0/24

```yaml
machine:
  type: controlplane
  kubelet:
    nodeIP:
      validSubnets:
        - 192.168.100.0/24
```
and
```yaml
cluster:
  controlPlane:
    endpoint: https://192.168.100.10:6443
```
also
```yaml
  etcd:
    advertisedSubnets:
      - 192.168.100.0/24
``` 

Thank you!
