### ISSUE TITLE
Bootstrap failing with `failed to verify certificate: x509`

### ISSUE THREAD

**Issue by Nikola-Milovic** [aenix-io/talm#61]
I would've submitted a discussion since its more of an question rather than an issue

(`$cp1ip` is just shorthand for `192.168.102.x`)

This is running on vagrant and libvirt, bootstraping a cluster via `talosctl` when using `talosctl gen config` works fine, but I wanted to give `talm` a try

What I did
1. `talm init`
2. Setup the talosconfig and the endpoint
```
> export TALOSCONFIG=$(realpath ./talosconfig)
> talosctl config endpoint $cp1ip
```
3. Create templates
```
> talm template -e $cp1ip -n $cp1ip -t templates/controlplane.yaml -i > nodes/cp1.yaml
> talm template -e $w1ip -n $w1ip -t templates/worker.yaml -i > nodes/w1.yaml
```
4. Apply configs
```
 > talm apply -f ./nodes/cp1.yaml -i
- talm: file=./nodes/cp1.yaml, nodes=[192.168.121.90], endpoints=[192.168.121.90]
> talm apply -f ./nodes/w1.yaml -i
- talm: file=./nodes/w1.yaml, nodes=[192.168.121.6], endpoints=[192.168.121.6]
```
5. Bootstrap
```
> talm bootstrap -f ./nodes/cp1.yaml
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake
 failed: tls: failed to verify certificate: x509: certificate signed by unknown authority" 
```

**Comment by kvaps** [comment]
Hey, Talm is storing `talosconfig` in the same directroy with the project, you can copy your talosconfig into root project directory, or override path in `Chartt.yaml`

**Comment by veith4f** [comment]
@lb0o What does "default network" mean?

here is my values.yaml

```
endpoint: "https://192.168.178.159:6443"
clusterDomain: cozy.local
floatingIP: 192.168.178.99
image: "ghcr.io/cozystack/cozystack/talos:v1.12.6"
podSubnets:
- 10.244.0.0/16
serviceSubnets:
- 10.96.0.0/16
advertisedSubnets:
- 192.168.178.0/24
oidcIssuerUrl: ""
certSANs: []
nr_hugepages: 0
allocateNodeCIDRs: true
```

here is my full node1.yaml

```
# talm: nodes=["192.168.178.159"], endpoints=["192.168.178.159"], templates=["templates/controlplane.yaml"]
# THIS FILE IS AUTOGENERATED. PREFER TEMPLATE EDITS OVER MANUAL ONES.
machine:
  type: controlplane # Defines the role of the machine within the cluster.
  # token: kfs1gy.w0ctpkk02cpcy4ew # The `token` is used by a machine to join the PKI of the cluster.
  # # The root certificate authority of the PKI.
  # ca:
  #   crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEFGdEs0dTRqMHVaUHV2S2h6VEwzMkVNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTBNRFF3T1RJeE5EQmFGdzB6TmpBME1ERXdPVEl4TkRCYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBRlJwTGVKU1MxZ3hQMWJtYnBWOWFUNGZtNDZUY0xmSDRFczJ5CkFyMkxadFNqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVZlR1dDUrOHVxSi9DdGErcwpMSEVNRmwwTCtDd3dCUVlESzJWd0EwRUFiMjFoM3hZZHQ5alR3V1ZrdEhJRlFNUHJ1d2lpRGgraVNaR3o3YVhJCkNwdG5mbFhmU040VEpTZXdDek8vaFhmSllkdmZXNG1LS3JTWDQ2Q0ZPMFZxQlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  #   key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJUHFaRmNvTStQQThaRGM1S3FHSnBDSWlTallNdnBKU3o5bG5GckFVSUM0NQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
  # # Extra certificate subject alternative names for the machine's certificate.
  certSANs:
    - 127.0.0.1
  kubelet:
    extraConfig:
      cpuManagerPolicy: static
      maxPods: 512
    nodeIP:
      validSubnets:
        - 192.168.100.0/24        

  network:
    hostname: talos-a7053
    interfaces:
      - interface: enp0s3
        addresses:
          - 192.168.178.159/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1
        vip:
          ip: 192.168.178.99
    nameservers:
      - 8.8.8.8
      - 8.8.4.4

  install:
    disk: /dev/sda
    image: ghcr.io/cozystack/cozystack/talos:v1.12.6
    wipe: true

  files:
    - content: |
        [plugins]
          [plugins."io.containerd.grpc.v1.cri"]
            device_ownership_from_security_context = true
          [plugins."io.containerd.cri.v1.runtime"]
            device_ownership_from_security_context = true
      permissions: 0o0
      path: /etc/cri/conf.d/20-customization.part
      op: create
    - content: |
        backup {
          backup = 0
          archive = 0
        }
        devices {
           global_filter = [ "r|^/dev/drbd.*|", "r|^/dev/dm-.*|", "r|^/dev/zd.*|" ]
        }
      permissions: 0o644
      path: /etc/lvm/lvm.conf
      op: overwrite
  sysctls:
    net.ipv4.neigh.default.gc_thresh1: "4096"
    net.ipv4.neigh.default.gc_thresh2: "8192"
    net.ipv4.neigh.default.gc_thresh3: "16384"
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://mirror.gcr.io
  kernel:
    modules:
      - name: openvswitch
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: zfs
      - name: spl
      - name: vfio_pci
      - name: vfio_iommu_type1
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete
    
# Provides cluster specific configuration options.
cluster:
  # id: soNArMT6M0JMlBzxP1mC0QPqB5v8w4QaKm5Fmh04FFE= # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
  # secret: v+3X5QWHTq5tC/oQtGoYKOdL4+UiA9LPOIx0O4nlOec= # Shared secret of cluster (base64 encoded random 32 bytes).
  # token: as1il1.d866jj6repl2d2is # The [bootstrap token](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) used to join the cluster.
  # secretboxEncryptionSecret: pQAxYrTg1W16zrACdIfpyAOoY8Ng+ar25EqbgWSwJ8Y= # A key used for the [encryption of secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).
  # ca:
  #   crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVRDZ0F3SUJBZ0lSQUxGU1ZCbUM4K3l3NjdHLzhpTnhGZmd3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEwTURRd09USXhOREJhRncwek5qQTBNREV3T1RJeApOREJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRSNlVUdEdxT08vQ01CYjU1cCt2Tnkzemx3bWRDMFZuVGNGblVLbldzT0puem44TFdIRTAyZ0VsSkkKMzdSODA4M2p1TmdqM1huSWhsUnNuNGV5dlJBaW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQUx0NlRaR2psK3NYb3QrMjhtdUR5QmhmK1dkTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUFXOER0U0cKNXErN3NZRE16U0M4Q3dkdE0xeHBCTnpSbHJxRFBnaUg3bk1hQWlBRGpzak1nRElRV3p5TXc1RmNGckVPcWVhcgphaDY5Z29rOExWeWZGNEw5enc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  #   key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUk5eHBFZ0tweEVGdlkvTVNKcWw2TG1pNWZMZUZuRDBZVkZ6T2xvMVJOV05vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMGVsRTdScWpqdndqQVcrZWFmcnpjdDg1Y0puUXRGWjAzQloxQ3AxckRpWjg1L0MxaHhOTgpvQkpTU04rMGZOUE40N2pZSTkxNXlJWlViSitIc3IwUUlnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  # # The base64 encoded aggregator certificate authority used by Kubernetes for front-proxy certificate generation.
  # aggregatorCA:
  #   crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYakNDQVFXZ0F3SUJBZ0lRUlZpYmVvcklNMEdxZlhvTjAwcVZHakFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMk1EUXdOREE1TWpFME1Gb1hEVE0yTURRd01UQTVNakUwTUZvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSUFRR2ZsbGQyMlVBUEl2T2xCVllrTWIzK3VYbUo1di8rb3g2cDZ1UTFUc1JndUZGRm5ECkN0WkxqdVRPWCsrY2NqYXQ1SExQeXFaRXJKYUpyb2R1dXZPallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVUwU25ORDhIUTJhWllENTZKNm5mU0JIcmhWWGN3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnCmROb3ZLNWg1b0tKNUZvTmZzb204QWJLbnZIQnBNY20zU0R1blkvM2hqbUFDSUdtMzltbHJVUG5HemY5dWRTZW0KWXRRR0srQ2g3UE9HZlNaOWZDS3YxZ2ZPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  #   key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURvTVM4MVVaVVFndVp4N3RDekU3QVhmamFrdlJGSVM0d2hJL0NzR0lQdEZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZ0JBWitXVjNiWlFBOGk4NlVGVmlReHZmNjVlWW5tLy82akhxbnE1RFZPeEdDNFVVV2NNSwoxa3VPNU01Zjc1eHlOcTNrY3MvS3BrU3Nsb211aDI2Njh3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  # # The base64 encoded private key for service account token generation.
  # serviceAccount:
  #   key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBcDZxdFlqTGF1Tm94VWYydGxLeU8xbVBZSnJjdENXUk9jenROOWxSeWJxTXRjQlAvCjZEaDVuZHhnRVh3MWFQWThiTlphQ1I0SVpXd0hYNGNnT2d6YlJWdW54V2pGNFdEMjhhU01GVmNIN2JsR2M5VTkKQkRsRm5EVTFBNzdqTGFUTUw3M0V6NE55Vk9NTm14L245MHl0WGJXbE1JQ3kyZ1pqc0Y1ZzFvOUJiYWdhMFB3bwp5ZjlZdWFkc2wwM1B5QlhOVVZQekJzR3d1eTdrQkhSUHZOVnBVNFcyNUhxREYzS2FRSUlIUUU0cnB4Nzh2ejdvCm9vU0NYVStFZysyVjNySXhjWlZOM1dmYkJhSDdTZGdXMUNFQTVjeitiSjBmL05JY0xoS2didUprK3ptTHhUSDYKckFsNnRTTHNkc2hudFhZNHRFUER1ejIxWEUxeUVyMXVCS2V1ZThsbFZ0SGErR2FNNjYwSzlWSnlsbXY2b2JkcwpRZ2ZTN2h1UW42d2RXTTJPWUowMUg3b1FqQkNQcVNmbEFWdnlmTFBtMkd6R3cvN2VXRVlETlhsdjkvd3pjWE1hCkxFOWJLNHpOMzUzSVZlaCtQdXVIU0x5RWJkL3oxUzBQek9TcitFLzFtNEhlaFkzUitFVGc2WStPcEdKU1JzSjEKT2EyVlB4SUZsNWY1TUEzLzNSN2VqSDdTRHRSdkprb2QzdURuRVVHMlNIWmFZc3RlaHIwNEd0VXo4UytoenpTUApxOGZVOG1iRk05cmM4V0xnYmhmTVhYTlNNYy8vdGRNeHRNYVA3VVpLbDlFaEJVVTRscTcrR1h2NmJVTm1xNTRzClR6V2pyL0toQlBSV1Q5bnEwUENPTnVGZXYvZHpmc1pQVEczRG5CNWF0dkVBSDNsNEFuaFFvaXRhQ2kwQ0F3RUEKQVFLQ0FnQThoaktmaTU4RDhwT3lOc0kxdEpLOVZuNTgvMHV0STczai8rajFQbWV1ZzQ0UDh0QkNtanhnbldBNgpmNTFpSGQwVEpzK0trZ0pTNWt2RkVxaXgrOWtkY09nZnJXSWRLUjBMZnF3b3VlbDlTWS9pbVh1MHJoM3dOUTdGCm90OHNKMXlqOFR0OTgwUE8yOFdhRlVydHJRcTZGS3VrVmhqNTlpdC9TNXBtYVlFalhmY01NTEppdEovcEtNUmMKMi9SaEZHbXc3WDZCbG1LL056Nk5VeFZEbzhBcEs5QXBLd1p1Yk9xODFaTmJoYnhoVUNESndxSkVwRlBRN2piMgpUc24yZ1ZteTJFUXE0K1llNHVtc3J1b1N1alV5UHkwcXRRK0tlcWc4ZzNIUmhUMFJxU1RJMHZGYnIvSlJOK0duClFWR2FvaW4yL0sxSHhvOVUyZ29QTkwxbHhjZ0lobUpEcld0Q0lFTy9iOGNLNkkvM25hSndsaDh0RVR5QTNHRUMKa2xEYThXbTJQQjI2ZGM1ZSszUXRFRGlpaTZYQWR0S2h6Z2tQdDMvcnFpa3gvYmtjMmtZV204VXJIRXF6REd6SwpGNVFZS0g0WlZPV2NCWW1xeDkwYVhGLzQzZnl3c1ZkVHlJK09ya0RsVjRSM0lCNWxFb3lOZjJvajZlL3Jmb3dzCkQ5dzlJeG53dWVQelZVbi9aS1Y1d0UrcGV4Q2NXZy9vejBKWmI4NkFUM201Wlp4eEE5WEVTWnFKZ09CR3ZvZmUKZHEyMWt0V29GMWh5UFFkR3NtRVNCeWVtRVZKd3BoaWgvb2ozNi9VZE9MYTBsK2Y4UDRTVjc4TTdkQkRCOXRwWgoxRnJnYkN4aVFUaDdFT0ZYTXV5Zzk0K0FkeGdsL1hLRk80YVJxMG1nWC9uZEJhV1Bld0tDQVFFQXdKOTJreG1MCjRWQWpLY2dHZEs3cnlhSHk1cm4yVmVaZmNTc1QyajAwSGl4bjJRaXJSTllnYVJkaExHUlhkZGFvekpGRWk2WGMKMlJ1SjVlUjBUNWdVZGtBdld2UFd5UmxmNlphckw2dkM0RjZoMVp3WHBTdzBNYVFNRURjY05TWWxrVVp6Vm53WApqL0tROCs2b2J6ck4rYVJEQUZUdGhrKy9QM05kckM4amxMUzcvTGdxYlc5dzJlYmpHeDBrbVhxS3libWR0bDJwCkgvN2Ryck1HaTV2ZmpmaHYwMnBwZDNQekRIQ0VWczROYzRJRmI0UFF2VVIwSCtUYkVZWE5YakxlaEluSUEycFEKaGM1Z2hqQ1R1OGhVVHhCUlVtTkUwSDJaTWZWQmxRNWY5TmN2YlVvMzFmeUp3eUdKalQ3SnNTVkE1QmRsMmlITAphV3FNOGdTb2FaT1Rtd0tDQVFFQTN0VXFYaDJrQ2E3K0J6Yk9WNk5pb29wa2dDM2x4d3BuL2dka2N2eDI5ejBOCjBoTGc0U1lYQ1A1RWpEK3c0WDJEa296TDJ1aG9ud2dOMERDM1JodGM1Tk1sMmxJSDYrRkVnMk1jZDk3SEpveXoKOUw5T3haZzZoNi9oUDlhWCswVVAvSXJ5dkhMSWVzNklUNGFCMmd0VmlvYmFScWZ2c25oc2tubmZTSUdzQUFWSgpXM044Z2JSZnQ4b0l2YjZzSzljSVkrazVEbXF4U0FsbUZkRjdvdGU5SXkwYzFpbE1yOXNVYWF5RDI0NC9HaTRRCi91TzlURklVUXFoUWN4L3JmTTlVSlk3NEEwK2J5aWVKRSs5bEFxV3RCNzNIL2JoYUpoVEh2RjI4VjNkSUlvZ2gKcnB0Zy81M2czY3FJZVdyNWlQMXJNdEFCVjhEKzVaZkMvMEgrUU1QcDF3S0NBUUE1ZU5yR05SOFpVUEhNNjVPUgppUWR0RjljRHBJU3RTSms5aU43WmhOMWlDMW5JMWQ5VUlKZDNBN1RJcS8rMGR5SFNONTIrRlBUNkNrOXd1bU5CCnhGeUdrOHdOVlNmR3hMMXJVcnNzOUJDbkpWVWdDUHk5R1oxUkdtTkhDMHB0U1Q1NFJBN3h4UUM2d0dNamhSZlkKYURGQXhSUUFxMVpiZHJ2WFVMS29SMEJVaEVCNnZQQmJ5cDVmUlphSlpuNmZGSU1JZ1V0Zk9EN1gveEZocUtUUgpUdWE2MDE5Nk13dll5azNBYm1udUJIamE5L1pyT1djMHNaSDhXaXBLNWlOS2NkOFdxSTEzQjJlVEpPcUQzMGFWCkJzYXcrR3RySzVkQ3BkYnBvd1c0Vlp1bnovU2twVHBYckl2bUhzR04xU2dVcE1yaHcyRnVYaHIxRHdlU3huVUIKV3pqMUFvSUJBUUMybUlpeVBLbTV3YXFwc0xCZlFpUkdPdzlsdGJhUFpxaVdrZW92QzFCVkFyTzdpL3E0cEdURgoyczNDKzBIdlZOR25HamJGK0NJYkJ4ZUNuUmpobXZTQkVjRDM2TFpUQlBJR2xBVzArRm5LN2d0Y3FCTmRlWU9rCndtdmF5dmNaVUp0ci8xUXZOZ093Rm1PK2Z1TVRFS3lVNmpJZEtlb1NIZm9pQVRvRmlUU3ZnNlY4Q2VOaHliT1IKd0QxdmRycFE1bEVheGZjYUtEV0RhU2c5QXI3RVR2TE95MTNRNUdEUnpiMHBadE5aNjNNcitjbTFoRnNQR2tjOQo0L3lnaWV5SEJzSFdVUlJNYWtTbjM4UEZFU3Q5Z3RPSi8yck5MdTY0TzlqOE12ZHQyUEhFVWpiL2hKVjBnU1BOCnV2UWdRcGVlT01OS0RRYThxUXAyaXVpZ0VLek8xM3RiQW9JQkFRQzBvSzVDWE9TQkc0bG1sTEpUSTBkQ01tbUsKdG5DVG9VdHFVT0h3M3JHNENlb2pNNlgzUHZxOVo2clN2NmxUeXpTZEJLTndnSllGTHo5MjRsK3lkblRDNlJqMApoTTZHS1dPKzYrZVJsVEFWZjJDZnRZUVJMakl0MzhxWHpXNGwwNzlVRExnZy92NmFCNzZWdWtJVEVuSWFMNzdkCnpQVXhPNXc4dnlVZUZKQU53Q0NGZFU5bjQvazM5U2RuT0ZWVGU4VkpYNGNLck5tUUt3TkpzRFluM2dGcCtaakcKV3pvVHBMQTJ2UXpVMUF5Z1pRbnNTbTRrUFNPYmxFMU9oY2tsU3IzazlFV1hhbVIvZm1RaDFaay8wVFB4N2JvWAoyUUN5Smg5R2RXaHhCVVRYSytzVUNqcEVGNDQva0tBSlV3cHIxWno0NFdEN2pteW4yaldJUmhXbGZjdjUKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  controlPlane:
    endpoint: https://192.168.178.159:6443 
  clusterName: cozystack 
  network:
    cni:
      name: none
    dnsDomain: cozy.local # The domain used by Kubernetes DNS.
    # podSubnets:
    #   - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/16
  apiServer:
    certSANs:
      - 127.0.0.1
  controllerManager:
    extraArgs:
      allocate-node-cidrs: "true"
      bind-address: 0.0.0.0
      cluster-cidr: 10.244.0.0/16
  proxy:
    disabled: true
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
  discovery:
    enabled: false
    # enabled: true # Enable the cluster membership discovery feature.
    # registries:
    #   kubernetes:
    #       disabled: true # Disable Kubernetes discovery registry.
    #   service: {}
  etcd:
    # ca:
    #   crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNPZ0F3SUJBZ0lRWFpORzlNUlF4SHBkWFc1T1c5WWRxekFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURRd05EQTVNakUwTUZvWERUTTJNRFF3TVRBNU1qRTBNRm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk1CMGVVbFExbmx3ClZGYUlrN2QzN3V6YlVrZlFSNE9sQktPd2lxTU5LRWZlZGxjRHU2Z1diV0FzOWNKZjRhM3RvL1h5ckc2QnJJTjkKK3FJUTU4SDNxZzJqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUTZOTjVDeWFNODJtCkJoRUpEV2k5dzd5K1J1VXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWdlTWpTank3MVVwYjNqRFdqMFhkK2VUUEYKOWZWNmhvWHJIUXZxOVZQQ1BLUUNJUUNMV2dTMk9RVGljSzl6WXZvY3hCM3ZBRTJVYzBobmVBVUFnNkk4SnFVTgpIZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    #   key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdkb0lDMHJ2eTRXMTVEUDl0SXNFR0NwRHpra0xIeEhmTHViWThHQytkV2dvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFd0hSNVNWRFdlWEJVVm9pVHQzZnU3TnRTUjlCSGc2VUVvN0NLb3cwb1I5NTJWd083cUJadApZQ3oxd2wvaHJlMmo5ZktzYm9Hc2czMzZvaERud2ZlcURRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    advertisedSubnets:
      - 192.168.178.0/24
  allowSchedulingOnControlPlanes: true
```
